### PR TITLE
fix(api): fix OverlayView

### LINKED ISSUE #882: OverlayView has wrong position by default on Safari if using getPixelPositionOffset props function
# Issue template

Hello!  I have some issue with api on Safari (Chrome, Firefox, Microsoft Edge work good). OverlayView has wrong position by default (getPixelPositionOffset does not work). After scroll map position reset to correct value.

           <OverlayView
            position={coordinate}
            mapPaneName={OverlayView.OVERLAY_MOUSE_TARGET}
            getPixelPositionOffset={(width, height) => (  { x: -width/2, y: -height } )}
          > 
          <button
          className="Button"
          type='button'
          onClick={this.handleButtonClick}
          >
          Test Overlay
          </button>
         </OverlayView>

For map investigation I used code from https://codesandbox.io/s/94o34

## Your Environment

os: mac

react version 16.13.1

@babel version 6.26.0

@react-google-maps/api version 1.9.1

## How is it behave?
OverlayView bottom/center is not over coordinate on Safari. OverlayView position fix after map zooming.
## How should it behave correctly?
OverlayView bottom/center is over coordinate on Safari.

### PR DESCRIPTION
**Pull request by breeze9527**
- fix render of OverlayView component
- update type definition of mapPaneName
- update script of react-google-maps-api-gatsby-example (for window compatibility)
- update OverlayView example

Fixes #882

### CODE REVIEW

File: packages/react-google-maps-api-gatsby-example/src/examples/example-overlay-view.js [hunk 1]
```diff
@@ -43,17 +56,61 @@ const ExampleOverlayView = ({ styles }) => {
           <Marker position={mapCenter} onClick={changeIsShown} />
           {isShown && (
             <OverlayView
-              position={mapCenter}
-              mapPaneName={OverlayView.OVERLAY_MOUSE_TARGET}
+              position={overlayPosition}
+              mapPaneName={overlayPane}
+              onLoad={(e) => {
```
Comment (JustFly1984) [inline packages/react-google-maps-api-gatsby-example/src/examples/example-overlay-view.js:61]: please extract to useCallback

File: packages/react-google-maps-api-gatsby-example/src/examples/example-overlay-view.js [hunk 2]
```diff
@@ -43,17 +56,61 @@ const ExampleOverlayView = ({ styles }) => {
...
+                console.log('onLoad: ', e)
+              }}
+              onUnmount={(e) => {
+                console.log('onUnmount: ', e)
+              }}
```
Comment (JustFly1984) [inline packages/react-google-maps-api-gatsby-example/src/examples/example-overlay-view.js:66]: please extract to useCallback

Comment (JustFly1984) [inline packages/react-google-maps-api-gatsby-example/src/examples/example-overlay-view.js:66]: please extract to useCallback

File: packages/react-google-maps-api-gatsby-example/src/examples/example-overlay-view.js [hunk 3]
```diff
@@ -43,17 +56,61 @@ const ExampleOverlayView = ({ styles }) => {
           <Marker position={mapCenter} onClick={changeIsShown} />
           {isShown && (
             <OverlayView
-              position={mapCenter}
-              mapPaneName={OverlayView.OVERLAY_MOUSE_TARGET}
+              position={overlayPosition}
+              mapPaneName={overlayPane}
+              onLoad={(e) => {
+                console.log('onLoad: ', e)
+              }}
```
Comment (JustFly1984) [inline packages/react-google-maps-api-gatsby-example/src/examples/example-overlay-view.js:63]: please extract to useCallback

File: packages/react-google-maps-api-gatsby-example/src/examples/example-overlay-view.js [hunk 4]
```diff
@@ -43,17 +56,61 @@ const ExampleOverlayView = ({ styles }) => {
...
       </div>
+
+      <div className='form-group custom-control custom-radio'>
+        <input
+          id='MARKER_LAYER'
+          className='custom-control-input'
+          type='radio'
+          name='overlayPane'
+          checked={overlayPane === OverlayView.MARKER_LAYER}
+          onChange={setOverlayPane.bind(undefined, OverlayView.MARKER_LAYER)}
```
Comment (JustFly1984) [inline packages/react-google-maps-api-gatsby-example/src/examples/example-overlay-view.js:84]: please extract to useCallback

File: packages/react-google-maps-api/src/components/dom/OverlayView.tsx [hunk 5]
```diff
@@ -161,35 +150,32 @@ export class OverlayView extends React.PureComponent<OverlayViewProps, OverlayVi
...
-        <div ref={this.containerRef} style={{ ...this.state.containerStyle, position: 'absolute' }}>
-          <ContentMountHandler onLoad={this.setOverlayViewCallback}>
-            {React.Children.only(this.props.children)}
-          </ContentMountHandler>
+    const paneEl = this.state.paneEl
+    if (paneEl) {
+      return ReactDOM.createPortal(
+        <div
+          ref={this.containerRef}
+          style={{ ...this.state.containerStyle, position: 'absolute' }}
```
Comment (JustFly1984) [inline packages/react-google-maps-api/src/components/dom/OverlayView.tsx:170]: please extract to useMemo

Comment (JustFly1984) [reply packages/react-google-maps-api/src/components/dom/OverlayView.tsx:170]: may be better use className instead of style. I'm working on CSP, and most secure settings require to disable inline-styles.
Currently inline styles is legacy from other projects. Not requirement, just a notice.

**Review by JustFly1984 — CHANGES_REQUESTED** [review]
Please read comments. After fixes I will merge and release new version

File: packages/react-google-maps-api/src/components/dom/OverlayView.tsx (hunk 5 above)
Comment (breeze9527) [reply packages/react-google-maps-api/src/components/dom/OverlayView.tsx]: Is difficult to set dynamic style with className, if you know how to do that, please let me know

**Comment by breeze9527** [comment]
Thank for you review

**Review by JustFly1984 — APPROVED** [review]

File: packages/react-google-maps-api/src/components/dom/OverlayView.tsx [hunk 6]
```diff
@@ -126,32 +128,25 @@ export class OverlayView extends React.PureComponent<OverlayViewProps, OverlayVi
 
   onRemove = (): void => {
     this.mapPaneEl = null
```
Comment (JustFly1984) [inline packages/react-google-maps-api/src/components/dom/OverlayView.tsx:130]: Here is typescript error, at least in TS@4.0.2. I have replaced this line with:
```
this.setState(() => ({
      paneEl: null
    }))
``` 
to publish 1.10.0
